version: '3.8'

services:
  web:
    build: .
    container_name: dostartup
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    ports:
      -  3001:3000
    restart: unless-stopped

# Usage:
#   docker compose up -d --build
#   docker compose logs -f
#   docker compose down
